load("@rules_cc//cc:defs.bzl", "cc_library")


cc_library(
    name = "mtl",
    srcs = [],
    hdrs = [
        "algorithm.hpp",
        "dyn_array.hpp",
        #"hash_map.hpp",
        "iterator.hpp",
        #"linked_list.hpp",
        "maybe.hpp",
        "move_only.hpp",
        "pointers.hpp",
        "result.hpp",
        "static_array.hpp",
        "types.hpp",
        "wrapped_var.hpp",
    ],
    visibility = ["//test:__pkg__"],
)
